[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-yaml" },
  { id = "check-merge-conflict" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "v0.9.20"
hooks = [
  { id = "tombi-format" },
  { id = "tombi-lint" },
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.12"
hooks = [
  { id = "actionlint" },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.33.1"
hooks = [
  { id = "typos", args = ["--force-exclude"] },
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "validate-pre-commit-manifest",
    name = "validate-pre-commit-manifest",
    entry = "prek validate-manifest .pre-commit-hooks.yaml",
    language = "system",
    files = "^\\.pre-commit-hooks\\.yaml$",
    pass_filenames = false,
  },
]
